---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-data-generator
data:
  config.yml: |
    ---
    config:
      - name: pkb_counter_1
        description: foo
        type: counter
        labels: [name, color]
        sequence:
          - time: 5
            values: 0-20
            operation: inc
            labels:
              name: apple
              color: red
          - time: 5
            eval_time: 1
            values: 0-20
            operation: inc
            labels:
              name: apple
              color: green
          - time: 5
            eval_time: 1
            value: 3
            operation: inc
            labels:
              name: apple
              color: yellow
